name: projeto_mobile_faculdade
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: 10.8.0
  url_launcher: ^6.3.1
  flutter_cube: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Adicione a seção assets para incluir a imagem
  assets:
    - lib/assets/notebook.jpg
    - lib/assets/3d_models/almofada.obj
    - lib/assets/3d_models/notebook.obj
    - lib\assets\3d_models\almofada.mtl
    - lib/assets/3d_models/celular.obj
    - lib\assets\3d_models\texturas\almofadas.png
    - lib\assets\3d_models\almofada.mtl